[tool.poetry]
name = "ScandEval"
version = "9.3.2"
description = "Evaluation of pretrained language models on mono- or multilingual language tasks."
authors = ["Dan Saattrup Nielsen <dan.nielsen@alexandra.dk>"]
maintainers = [
    "Dan Saattrup Nielsen <dan.nielsen@alexandra.dk>",
    "Kenneth Enevoldsen <kenneth.enevoldsen@cas.au.dk>",
]
readme = "README.md"
license = "MIT"
homepage = "https://scandeval.github.io"
repository = "https://github.com/ScandEval/ScandEval"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
tqdm = "^4.62.0"
huggingface-hub = "^0.19.0"
datasets = "^2.15.0"
click = "^8.1.3"
termcolor = "^2.0.0"
numpy = "^1.23.0"
sentencepiece = "^0.1.96"
protobuf = "~3.20.0"
seqeval = "^1.2.2"
pandas = "^2.2.0"
python-dotenv = "^1.0.1"
sacremoses = "^0.1.1"
jax = "^0.4.24"
jaxlib = "^0.4.24"
flax = "^0.8.1"
pyinfer = "^0.0.3"
openai = "^1.11.1"
tiktoken = "^0.5.2"
levenshtein = "^0.24.0"
einops = "^0.7.0"
bitsandbytes = {markers="sys_platform != 'darwin' or platform_machine != 'arm64'", version = "^0.42.0"}
requests = "^2.31.0"
torch = "^2.1.1"
transformers = "~4.37.1"  # Only minor upgrades as breaking changes happen often
accelerate = "^0.26.0"
rouge-score = "^0.1.2"
bert-score = "^0.3.13"
evaluate = "^0.4.1"
vllm = {markers="sys_platform != 'darwin'", version = "^0.3.0"}
demjson3 = "^3.0.6"
pydantic = "^2.6.0"
lm-format-enforcer = "^0.8.2"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.4.0"
pre-commit = ">=3.3.3"
lxml = ">=4.9.3"
pytest-cov = ">=4.1.0"
readme-coverage-badger = ">=0.1.2"
ruff = ">=0.1.13"
mypy = ">=1.8.0"

[tool.poetry.scripts]
scandeval = "scandeval.cli:benchmark"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    '--verbose',
    '--durations=10',
    '--color=no',
    '-s',
    '-vv',
    '--doctest-modules',
    '--cov=src/scandeval',
]
xfail_strict = true
filterwarnings = [
    "error",
    "ignore::UserWarning",
    "ignore::DeprecationWarning",
    "ignore::ImportWarning",
]
log_cli_level = "info"
testpaths = ["tests", "src/scandeval"]

[tool.ruff]
line-length = 88
target-version = "py310"
extend-select = [
    "I",
    "D",
]
exclude = [
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".scandeval_cache",
    ".venv",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = true

[tool.ruff.isort]
split-on-trailing-comma = false

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["F401"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
