[tool.poetry]
name = "ScandEval"
version = "4.0.0"
description = "Evaluation of language models on mono- or multilingual Scandinavian language tasks."
authors = ["Dan Saattrup Nielsen <saattrupdan@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://scandeval.github.io"
repository = "https://github.com/saattrupdan/ScandEval"
include = [
    { path = "config/*.yaml", format = "wheel"},
    { path = "config/datasets/*.yaml", format = "wheel"},
    { path = "config/tasks/*.yaml", format = "wheel"}
]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
pdoc3 = "^0.10.0"
tqdm = "^4.62.3"
huggingface-hub = "^0.7.0"
transformers = "^4.17.0"
torch = "^1.9.0"
datasets = "^2.0.0"
click = "^8.1.3"
termcolor = "^1.1.0"
numpy = "^1.19.5"
sentencepiece = "^0.1.96"
protobuf = "^3.20.0"
seqeval = "^1.2.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pre-commit = "^2.17.0"
jupyterlab = "^3.4.2"
black = {extras = ["jupyter"], version = "^22.3.0"}

[tool.poetry.extras]
jax = ['jaxlib>=0.1.75', 'jax>=0.2.26', 'flax>=0.3.6']
spacy = ['spacy>=3.2.0', 'spacy-transformers>=1.1.6']
all = ['jaxlib>=0.1.75',
       'jax>=0.2.26',
       'flax>=0.3.6',
       'spacy>=3.2.0',
       'spacy-transformers>=1.1.6']

[tool.poetry.scripts]
scandeval = "scandeval.cli:benchmark"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ['--flake8',
           '--verbose',
           '--durations=10',
           '--color=yes',
           '-s',
           '-vv',
           '--doctest-modules']
xfail_strict = true
filterwarnings = ["error"]
log_cli_level = "info"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
	\.git
| \.hg
| \.mypy_cache
| \.tox
| \.venv
| _build
| buck-out
| build
)/
'''

[tool.isort]
profile = "black"
