name: 📚 Benchmark Dataset Request
description: Do you think a particular benchmark dataset is missing in ScandEval?
title: "[BENCHMARK DATASET REQUEST] "
labels: "benchmark dataset request"

body:
- type: textarea
  attributes:
    label: 📚 Describe the dataset
    description: |
      Include the name and a brief description of the dataset, along with a link to where it is currently hosted (doesn't have to be Hugging Face). Also include roughly how many samples the dataset contains, and what language it pertains to.
  validations:
    required: true
- type: textarea
  attributes:
    label: Rationale
    description: |
      Explain why you think it is important to include this dataset in ScandEval.
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
