name: 📚 Benchmark Dataset Request
description: Do you think a particular benchmark dataset is missing in ScandEval?
title: "[BENCHMARK DATASET REQUEST] "
labels: "benchmark dataset request"

body:
- type: textarea
  attributes:
    label: 📚 Describe the dataset
    description: |
      Include the name and a brief description of the dataset, along with a link to where it is currently hosted (doesn't have to be Hugging Face).
  validations:
    required: true
- type: textarea
  attributes:
    label: Rationale
    description: |
      Explain why you think it is important to include this dataset in ScandEval.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Dataset languages
    description: What languages is the dataset in?
    options:
      - label: Danish
      - label: Swedish
      - label: Norwegian (Bokmål or Nynorsk)
      - label: Icelandic
      - label: Faroese
      - label: German
      - label: Dutch
      - label: English
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
