name: 🐛 Benchmarking Bug Report
description: Have you experienced a bug using the `scandeval` package?
labels: bug

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/Scandeval/ScandEval/issues?q=is%3Aissue).
- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is. If relevant, add a minimal example so that we can reproduce the error by running the code.
  validations:
    required: true
- type: textarea
  attributes:
    label: Operating System
    description: For instance, MacOS, Ubuntu
  validations:
    required: true
- type: textarea
  attributes:
    label: Python version
    description: Output of `python --version`
  validations:
    required: true
- type: textarea
  attributes:
    label: Device
    description: For instance, CUDA GPU, AMD GPU, CPU, Mac M1
  validations:
    required: true
- type: textarea
  attributes:
    label: Packages installed
    description: Output of `pip list` or `poetry show`
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
