name: 📊 Model Evaluation Request
description: Would you like to have a particular model included in the leaderboards?
labels: "model evaluation request"

body:
- type: textarea
  attributes:
    label: 📊 Describe the model
    description: |
      Include the name and a brief description of the model, along with a Hugging Face link to it. Also include whether it is an encoder (BERT-style) model or a decoder (GPT-style) model, and what language(s) it should be benchmarked on.
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
